
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtfhsjqnjziuonmebvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZmhzanFuanppdW9ubWVidmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg2MjIxNjcsImV4cCI6MjAyNDE5ODE2N30.zqKRnH21qiOOlpAVbRr1Fk-PIO8_1c-0YHEskm3zGjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
