// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtfhsjqnjziuonmebvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZmhzanFuanppdW9ubWVidmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NDQ0MTYsImV4cCI6MjA1NDQyMDQxNn0.0V0uqWr1eqWkOCrl3a8q4O14WYsv3LEIfgbrl_Rn2Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);